### ISSUE TITLE
Crash with google login

### ISSUE THREAD

**Issue by AlexGagne10** [FloppyDiskUser/WeezBot#3]
Hi the bot crash only when I use google login. Thank you in advance for your help and your work ;)

**Comment by FloppyDiskUser** [comment]
Hey,
Is it crashing directly after quick setup? Or after you changed some of the configs

**Comment by AlexGagne10** [comment]
After I click start bot!

**Comment by FloppyDiskUser** [comment]
Did you try to reinstall?

**Comment by AlexGagne10** [comment]
Yes I try to reinstall and I do the update but when I start the boot it crash!

**Comment by FloppyDiskUser** [comment]
Hey are you connect to Internet over a proxy?

**Comment by AlexGagne10** [comment]
No! I think it because I reinstall Windows and I don't have Visual Basic. I will try to install Visual, maybe its just a missing dll !

**Comment by FloppyDiskUser** [comment]
Hey,
Thats a smart idea. Pls tell me the result of this

**Comment by FloppyDiskUser** [comment]
hey,
I just found out there is a Problem when you have a Mr. Mime . Maybe thats the Problem?

**Comment by AlexGagne10** [comment]
I don't have Mr.Mime! I reinstall Visual 2015 but the bot crash again. 
I got this error in Visual : 
System.Collections.Generic.KeyNotFoundException was unhandled
Message: An unhandled exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in mscorlib.dll
Additional information: La clé donnée était absente du dictionnaire.

I also reinstall Windows 10 and before I install update the bot work fine with google but after updating windows it crash again.

Sorry I speak very bad and english.

**Comment by FloppyDiskUser** [comment]
Hey,
I know whats your problem and im currently working on fixing it with the next update

**Comment by AlexGagne10** [comment]
Thank for the update.
I have only one problem. 
![capture](https://cloud.githubusercontent.com/assets/20649406/18495460/1b16017a-79ec-11e6-8843-e7f2a116221f.JPG)
Snipe always give me error.
Maybe you could add also a manual snipe.

**Comment by FloppyDiskUser** [comment]
@AlexGagne10 hey, good idea. Will be coming soon
